[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.4.0"
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"

[workspace.dependencies]
oci-wasm = "0.0.4"
tokio = "1.35.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
    "fmt",
    "env-filter",
] }
wasm-pkg-common = { version = "0.4.0", path = "crates/wasm-pkg-common" }
wasm-pkg-loader = { version = "0.4.0", path = "crates/wasm-pkg-loader" }
