[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.3.0"
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0 WITH LLVM-exception"

[workspace.dependencies]
tokio = "1.35.1"
tracing = "0.1.40"
wasm-pkg-loader = { version = "0.3.0", path = "crates/wasm-pkg-loader" }
